ONSdigital/rm-collection-exercise-service

- src/main/resources/database/changes/release-10.49.2/changelog.yml
- src/main/resources/database/changes/release-10.49.2/us004-fix-sequence.sql
When running up the collection exercise service locally
BRES_collectionexercise_seeddata.sql inserts a collection exercise with
a hardcoded id. This means the sequence doesn't get incremented
therefore the next time the api tries to insert a collection exercise
using the sequence it will fail.
This change should have any impact in production as it will either set
the sequence to what it currently is because it's greater than the 4.
The reason it has been set to 4 is because there are a couple more rows
in the dev database
1. Run up the ras-rm-docker-dev services using `make up`
1. Set the sequence to a number higher that 4 `SELECT SETVAL('collectionexercise.exercisepkseq', 100);`
1. Check out this branch in rm-collection-exercise-service
1. Run `mvn clean install` to build the new docker …
> Set sequence value to skip hardcoded ids

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/CollectionInstrumentClassifierTypes.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnits.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnitsTest.java
Every collection instrument has a survey ID that can be used to look up
collection instrument. This will mean that if there aren't any
classifiers defined the CI will be selected by SURVEY_ID
https://trello.com/c/E7LNNMuG/54-tbl124-required-for-bb-collection-exercise-publish-select-ci-for-survey-as-default
> Use the SURVEY_ID for CI lookup

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/ExceptionHandler.java
- src/main/resources/springintegration/collection-instrument-inbound.xml
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/ExceptionHandlerTests.java
Originally the message would be left on the queue if an error occurred
handling an incoming message on the Seft.Instruments queue.  This would
cause the message to be processed again and the error most likely
repeated.
This PR covers a change to remove the message from the Seft.Instruments
queue and drop an error to the Seft.Instruments.DLQ queue in the following format:
```{"collectionInstrument":"3360762f-1e3e-45f3-82ff-c0698820e71e","collectionExercise":"a9350d52-7613-42cf-bbec-a704d4388168","errorTimestamp":"1519306705553","errorMessage":"State Transition from READY_FOR_LIVE via CI_SAMPLE_ADDED is forbidden.","errorType":"BAD_REQUEST"}```
> Changed error handling to avoid infinite retry

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/CollectionExerciseEventInboundReceiver.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/schedule/SchedulerConfiguration.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/CollectionExerciseService.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImpl.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/change/ScheduleEvent.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/state/CollectionExerciseStateTransitionManagerFactory.java
- src/main/resources/springintegration/collex-event-messager-inbound.xml
- src/main/resources/springintegration/collex-event-messager-outbound.xml
- src/main/resources/springintegration/flows.xml
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/change/ScheduleEventTests.java
Implemented the transition from READY_FOR_LIVE to LIVE.  The collection exercise service now listens to messages on the collex-event-message-outbound-exchange and when a message with type Elapsed occurs for an event tag of go_live it will send a go_live event to the corresponding collection exercise state machine, hopefully putting the collection exercise into the LIVE state.  If the state is no READY_FOR_LIVE the event will bounce off and currently no other action is taken than an error will be logged (possibly needs more thought from the business)
> Us047 live state

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImpl.java
Trivially easy PR to review (hopefully).  This one stops the error message when a quartz event schedule fails from being usefully reported in the logs.
> Added cause to exception rethrow

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/CollectionInstrumentClassifierTypes.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/validation/CollectionInstrumentClassifierTypesTest.java
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/validation/CollectionInstrumentClassifierTypesTest.ExerciseSampleUnit.json
This PR adds FORM_TYPE classifier type as it was not getting used when fetching a collection instrument. 
Dependencies:
- https://github.com/ONSdigital/rm-survey-service/pull/27 (classifiers are fetched from this service but FORM_TYPE classifier currently is not in the DB until this PR goes in)
- Response operations should read form type from file name (WIP)
- Acceptance tests need to load a CI with form_type with it (WIP)
> use FORM_TYPE classifier

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/SampleServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseExecutionEndpointUnitTests.java
Stop linking parties to a collection exercise when the collection exercise is initially linked to the sample.
Instead do this link when collection exercise is executed. 
This fixes(improves at least) a problem with race conditions we were having and it will make it easier to change a sample in the future
> Defect-R17_2-Link parties to collection exercise at execution

- API.md
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/repository/SampleUnitRepository.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleService.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/SampleServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java
We should not be using the party data in this service to determine CE association.
Currently backstage is the only service using this endpoint, which is being removed in https://github.com/ONSdigital/ras-backstage/pull/105. I am removing the endpoint to avoid future misuse.
> Remove exercises by party id endpoint

- manifest-no-envs.yml
We need to override environmental variables at deployment time. If a
variables is specified in the manifest file it isn't being overriden.
> Create a manifest file with no envs

- docker-compose.yml
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/SurveySvcRestClientImpl.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/AppConfig.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/SampleUploadedInboundReceiver.java
- src/main/resources/application-test.yml
- src/main/resources/springintegration/flows.xml
- src/main/resources/springintegration/generic-collection-outbound-flow.xml
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseClient.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/SampleUploadedInboundReceiverTest.java
This is the second attempt to introduce integration tests to the collection exercise service.  The original attempt failed as it used a simple Java client to send rabbit messages.   This did not work as expected on cloud foundry so had to be backed out.  This version uses spring integration to drive the messaging so should configure ok on cloud foundry (same approach works on other services).
The integration tests that have been added have been designed to play nice with the standard docker setup so there should be no port clashes (i.e. the integration tests can be run at the same time as the full docker env)
This reverts commit 55cbda5b2fae24fa9a08b7ab602c5cd0641914e4.
- when a sample link is activated, a message is sent to collection-outbound-exchange
- an integration test has been …
> Added an integration test to test receiving sample upload finished messages

- docker-compose.yml
- pom.xml
- src/main/resources/application-test.yml
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointIT.java
- also made sure integration tests run with the test Spring profile
The method used to tell spring to use the test profile when running the integration tests was flawed, forcing a command line parameter to be used to make them work.  This is now fixed. Additionally the Rabbit UI was specified on a port that is sometimes used elsewhere so all Rabbit ports have been moved up the range to prevent clashes.
- @ActiveProfiles("test") annotation added to CollectionExerciseEndpointIT
- active profile removed from pom
- rabbit ports changed in docker-compose.yml and application-test.yml
- Run up the full ras-rm-docker-env services via make up or similar
- Run 'mvn clean install' for rm-collection-exercise-service
- Ensure all tests complete successfully
> Fixed possible port clash on integration tests

- .gitignore
- Makefile
- diagrams/collection-exercise-new-states.puml
- diagrams/collection-exercise-state.puml
This PR adds 2 plantuml state diagrams for collection exercises and the means to build them
No code has been changed but a Makefile has been added
```
make diagrams
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome diagrams/collection-exercise-new-states.svg
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome diagrams/collection-exercise-state.svg
```
Ensure diagrams can be viewed
> Added plantuml diagrams and means to build

- pom.xml
The integration tests are hit and miss and it's likely a timing issue
with action taking too long to start. We were waiting an arbitrary 10s
which might not have been enough.
This change uses a different maven plugin to check the healthcheck/info
api waiting up to 30 seconds for it to return a 200.
* Run `mvn install` observing the tests pass and the sections that are waiting for the service to be up
```
[INFO] --- http:1.0.0:wait (wait-for-action) @ collectionexercisesvc ---
[INFO] Waiting for http://localhost:38151/info
[INFO] Waited for 26093ms for http://localhost:38151/info
[INFO]
[INFO] --- http:1.0.0:wait (wait-for-survey) @ collectionexercisesvc ---
[INFO] Waiting for http://localhost:18080/info
[INFO] Waited for 109ms for http://localhost:18080/info
```
> Add wait in pre-integration-test

- pom.xml
We need to be able to skip the http wait when we're skipping the
integration tests otherwise it will cause failures when the services do
not start up.
https://github.com/tsundberg/maven-wait-plugin/pull/1 added in the
ability to skip the wait with -Dhttp.wait.skip
Bump the wait plugin version
1. Run `mvn install -Ddocker.skip -Ddockerfile.skip -Dhttp.wait.skip -DskipTests` on master and observe hang then failure
1. Run `mvn install -Ddocker.skip -Ddockerfile.skip -Dhttp.wait.skip -DskipTests` on master and
passing build
https://github.com/tsundberg/maven-wait-plugin/pull/1
> Bump http wait plugin for skip

- pom.xml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java
Return events when returning a collection exercise. Should mean fewer API calls.
Return events when returning collection exercise using collection exercise dto.
Add some logging.
Ran with api changes hit one of the get endpoints for a collection exercise check events are returned for a collection exercise with events.
[Trello] https://trello.com/c/PLkePSlW
Requires this to be merged first: 
https://github.com/ONSdigital/rm-collectionexercisesvc-api/pull/16
> Add implementation for events to be returned with collection exercise

- .travis.yml
Run fmt:check and integration tests in travis
* fmt:check will prevent code being merged that hasn't been formatted
* cobertura:cobertura-integration-test will make cobertura run
integration tests as they aren't being ran in travis at the moment
Check travis build logs to see has ran CollectionExerciseEndpointIT and `fmt-maven-plugin:2.5.0:check` in the logs
```
[INFO] --- fmt-maven-plugin:2.5.0:check (default-cli) @ collectionexercisesvc ---
[debug] Using Google style
[INFO] Processed 92 files (0 non-complying).
```
https://trello.com/c/WnTGaznV/152-rm-collection-exercise-service-integration-tests-are-not-running-in-travis
> Run fmt:check and integration tests in travis

- .travis.yml
Travis will run mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V on the install step by default which runs the integration tests
and builds the docker containers which makes the build take twice as
long. Changing it to skip docker and integration tests
https://docs.travis-ci.com/user/languages/java/
Add install phase that skips docker and integration tests
Check integration tests aren't ran in `install` step on travis
https://docs.travis-ci.com/user/languages/java/
> Stop IT running twice

- manifest-no-envs.yml
to 1.5Gb (1536Mb)
The collection exercise service in the cloudfoundry CI space has taken to crashing regularly (pretty much every time the acceptance tests are run 2-3 times).  Careful analysis showed that it was running out of memory (metaspace to be precise).  Although the exact cause is currently unknown, the service has been running near the limit for some time so we decided it best to increase the amount of memory allocated to this service from 1Gb to 1.5Gb
- increase the memory parameter in the cloudfoundy manifest file to 1.5Gb from 1Gb
- cf app rm-collection-exercise-service-ci 
- check memory usage in output
> Increased memory allocated to collection exercise service in cf

- pom.xml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/ActionSvcClient.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/ActionSvcRestClientImpl.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/ActionSvcClientImplTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImplTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/SampleServiceImplTest.java
When we remove BI cases we will stop using `casetypeoverrides` and instead use the action plan selectors which have been recently added to the action service.
When we initially create action plans we will want to also create the appropriate action plan selectors
Added selectors fields to requests for creating override action plans
The selectors we are concerned with are `surveyRef`, `activeEnrolments` and `exerciseRef`
After running `make setup` in the acceptance tests the created action plans in the database should have it's `selectors` fields filled in
To test for a single case exercise the create collection exercise endpoint either directly or through the UI and check that action plans are created with the appropriate selectors …
> Remove bi/create actionplan selectors at ce creation

- .editorconfig
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/ActionSvcClient.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/ActionSvcRestClientImpl.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/ActionSvc.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/ActionRuleCreator.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImpl.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/GoLiveActionRuleCreator.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/MpsActionRuleCreator.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/ReminderActionRuleCreator.java
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/EventServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/ActionSvcClientImplTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImplTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/GoLiveActionRuleCreatorTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/MpsActionRuleCreatorTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/ReminderActionRuleCreatorTest.java
Currently there is nothing to automatically create the action rules that
cause letters and emails to be sent when a collection exercise's events
are created. This will fix that so letters & emails will be sent without
manual intervention.
Updating these dates is out of scope for this ticket.
https://trello.com/c/Eknzy8H2/119-tbl123-link-action-rules-to-action-plans-at-create-time-create
Dependant on: ONSdigital/rm-action-service#69
> Create Action Rules when Events Created

- .travis.yml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/distribution/SampleUnitDistributorTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImplTest.java
Only publish a message when the collection exercise has been
transitioned not whenever the collection exercise is updated.
This was introduced https://github.com/ONSdigital/rm-collection-exercise-service/pull/80/files
1. Run `mvn install -Ddocker.keepRunning`
2. Go to http://localhost:46672/#/queues/%2F/Collex.Transition
3. There should only be 7 events and no duplicate states for the same collection exercise id
https://github.com/ONSdigital/rm-collection-exercise-service/pull/80/files
> Fix collection exercise transition message

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImplTest.java
Motivation and Context
======================
Currently when you create a social survey's collection exercise event
dates there is an exception. This is caused by assuming all
surveys are business surveys when creating action rules.
What has changed
================
This adds a check for if the survey is a business survey, removing the
automatic creation of action rules for non-business survey types.
How to test?
============
* Run Maven Test
* Create an event on a social survey
> Fix social survey event dates

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/ReminderActionRuleCreator.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/ReminderActionRuleCreatorTest.java
Currently we don't differentiate between the different reminder action
rules.
This will add a "+1", "+2", or "+3" to the action rules name for
the reminder, reminder2, and reminder3 event tags.
mvn test
> Correct Reminder Naming Convention

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImplTest.java
We were previously using `exerciseRef` and `surveyRef` as selectors for the actionplans. This made them more human readable but harder to work with in the code.
Selectors `exerciseRef` and `surveyRef` have been replaced with `collectionExerciseId`
Check that when creating a collection exericse that action plans are created with `collectionExerciseId` in the selectors field
Acceptance tests should pass
> Use collectionExerciseId as selector for action plans

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/ActionSvcClient.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/ActionSvcRestClientImpl.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/ActionSvcRestClientImplTest.java
A few people required this client function for what they are currently working on so this is being added independently so they have access to it
Added a client function for retrieving action plans from the action service using their selectors field
Tests should still pass
You could also exercise the function as part of a related piece of work
> Add client to get action plans by their selectors

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/ActionSvcRestClientImpl.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/ActionSvcRestClientImplTest.java
Call to action service was missing the authentication header.
This adds it in.
Test using this docker dev change (as the services do not check basic auth using the master branch)>> https://github.com/ONSdigital/ras-rm-docker-dev/pull/76
> Add missing headers in get action plans call

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/ActionSvcRestClientImpl.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/GoLiveActionRuleCreator.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/GoLiveActionRuleUpdater.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/MpsActionRuleCreator.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/MpsActionRuleUpdater.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/ReminderActionRuleCreator.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/ReminderActionRuleUpdater.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/ActionSvcClientImplTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/GoLiveActionRuleCreatorTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/GoLiveActionRuleUpdaterTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/MpsActionRuleCreatorTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/MpsActionRuleUpdaterTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/ReminderActionRuleCreatorTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/actionrule/ReminderActionRuleUpdaterTest.java
Call to action service was being done without an authentication header
resulting in 401s on event update. This pr adds the header into the
request. Also a number of unnecessary calls are being made to survey
service, changed the logic order so the calls are not being made
unless it is needed.
Added authentication header to action service call
Changed order for calling survey service to after the event tag check.
mvn test
ATs
> Add authentication header & remove unnecessary survey calls

- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointIT.java
Currently http requests to stubs hang intermittently.
Changing to WireMockClassRule instead of WireMockRule.
Run ITs a couple of times?
> Fix flakey integration tests

- manifest-template.yml
- pom.xml
actionsvc connection config was missing from the manifest-template. These are required for PROD/PREPROD deployments to override localhost env variables.
> Adding actionsvc connection config

- API.md
- scripts/collectionexercise_report.sql
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/CollectionExercise.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java
- src/main/resources/database/changelog-master.yml
- src/main/resources/database/changes/release-11/changelog.yml
- src/main/resources/database/changes/release-11/recreate_collectionexercise_report.sql
- src/main/resources/database/changes/release-11/remove_survey_name.sql
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImplTest.java
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/distribution/SampleUnitDistributorTest.Event.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/distribution/SampleUnitDistributorTest.ExerciseSampleUnitGroup.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.CollectionExercise.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.CollectionExercise.post.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.CollectionExerciseDTO.post-missing-survey.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.CollectionExerciseDTO.post-survey-ref.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.CollectionExerciseDTO.post.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.SurveyDTO.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImplTest.CollectionExercise.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImplTest.CollectionExerciseDTO.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnitsTest.CollectionExercise.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnitsTest.ExerciseSampleUnit.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnitsTest.ExerciseSampleUnitGroup.json
- src/test/resources/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnitsTest.SurveyDTO.json
Need this PR to be merged first for this to pass: https://github.com/ONSdigital/rm-collectionexercisesvc-api/pull/18
In context this PR is similar to: https://github.com/ONSdigital/ras-party/pull/152
Since the service name can be edited now, the one held in this service is not even the correct one i.e. out of date and the actual up to date survey details are stored in another service i.e. survey service
Card: https://trello.com/c/LP687BIU/331-remove-repeated-survey-name-from-services-other-than-survey-service-s
This PR aims to remove any ref of the survey name and drop the column entirely from the DB as well
- Run `mvn clean install` on collection-service-api then on rm-collection-exercise-service then do a `make up` on your `ras-rm-docker` then run `ras-party` locally to test all three …
> Remove references of survey name from across the service

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/validator/ReminderEventValidator.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/validator/ReminderEventValidatorTest.java
Currently reminder events that are in the past can not be updated,
which is a valid validation, but this check should only apply if the
collection exercise has been executed. This PR adds a check for CE
state before validating the reminder event has passed. Allowing a user
to update reminder events that have passed but not actually created any
notification files/emails.
Only validate existing reminder event hasn't passed if collection exercise has been executed.
Ran unit tests, integration tests and acceptance tests.
> Adjust reminder event validation

- pom.xml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/CollectionExerciseApplication.java
Bug discovered by @ajmaddaford in CI-latest where JSON not being used for key-value pairs.
Instead of flipping logging to use JSON in a `CommandLineRunner.run()` method, we're using a `@Postconstruct` instead, which should always fire.
Run with `--spring.profiles.active=cloud` or hack the `application.yml` to set `CLOUD` logger and `useJson=true`
Related Trello card: https://trello.com/c/KNOUa0pq/349-update-logging-in-all-java-services-to-use-key-value-pairs
> Init JSON logging in PostConstruct method

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/SampleUnitReceiverImpl.java
We are seeing an intermittent failure of the collection exercise service to process all the sample units sent from the sample unit service via Rabbit. Occasionally a message is Dead-Letter-Queued (DLQ'ed) and this results in the collection exercise getting into a hung state expecting all the sample units to arrive.
There is no useful logging to tell us why the message is being DLQ'ed, so this PR adds in a blanket catch-all-log-and-rethrow to help us diagnose this intermittant issue in all environments.
Added a catch clause to catch any exceptions at the moment before they would cause a Rabbit message to be DLQ'ed, and to log out the details.
Because this is an intermittent failure, the CI environment run by concourse is the place where we're most likely to see this. We should let the …
> Add log of unexpected exceptions in acceptSampleUnit

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/SampleServiceImpl.java
There is a race condition where `CollectionExerciseExecutionEndpoint.requestSampleUnits` makes a REST API call to Sample service to send all the sample units _before_ it has recorded the number of sample units it's expecting.
To fix this _properly_ will require a change to the sample service to get the number of sample units separately from the request for them to be sent - a new API method.
This is a stop-gap fix which will improve things, but does not [yet] eliminate every edge case.
Updated `SampleServiceImpl.acceptSampleUnit` to check to make sure we have an expected number of sample units before we do the comparison to see if we've received them all.
Obviously, there's a problem if they all get received very quickly, but this ought to fix our null pointer exceptions causing messages …
> Fix race condition by checking if value is null before comparison

- pom.xml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/SampleSvcClient.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/SampleSvcRestClientImpl.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/SampleSvc.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/CollexSampleCountUpdater.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/SampleServiceImpl.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/SampleSvcRestClientImplTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/CollexSampleCountUpdaterTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/SampleServiceImplTest.java
Presently the Collection Exercise service doesn't know how many sample units it expects to be sent by the Sample service until it requests the sample units to be sent, which causes a race condition - if the sample units start arriving before Collex has managed to store the expected number to the database.
This was causing intermittent failures in the CI pipeline and in production, and a temporary fix was to ignore the count check if we didn't have an expected value, but this fix was less than ideal, because the race condition still potentially existed for very small sample sizes.
This fix is intended to close all the loopholes by asking for the number of expected sample units _before_ they start to be sent by the Sample service. This is **one of three** related PRs.
Before instructing …
> Fix race condition on sample size

- API.md
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/repository/CollectionExerciseRepository.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/CollectionExerciseService.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java
We are currently filtering in the front end, to display only the live collection exercises. By adding an optional parameter to the REST API, we can simplify the front-end code and reduce the amount of data being transferred from DB -> Collex Service -> Front-end.
Added optional param to `CollectionExerciseEndpoint.getCollectionExercisesForSurvey`.
There's a new unit/REST test which covers this change.
To manually test, send a GET to `http://localhost:8145/collectionexercises/survey/{id}?liveOnly=true` and you should only receive collection exercises which are in the LIVE state.
Trello: https://trello.com/c/n7EcEA9y/344-add-ability-to-collection-exercise-to-only-return-live-collection-exercises-for-a-survey-m
> Add optional parameter to REST API to allow filter by only live collexes

- pom.xml
We recently had to do a bug fix off an earlier release and create a jar from it in artifactory. Because of that we are out of step and the snapshot version needs updating
> Update snapshot version to 10.49.21

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/SampleUnitReceiver.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleService.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnits.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnitsTest.java
With multiple instances of the Collection Exercise service running in production, it's theoretically possible that the final couple of messages could be processed simultaneously, in which case the collection exercise would never transition from EXECUTION_STARTED to EXECUTED and trigger validation on the poller, because the expected number of sample units isn't reached by a single thread in a single process, in the event of a dead-heat.
Although this hasn't been seen definitely 'in the wild' it's theoretically possible and a fix was trivial. Multiple other fixes have gone in for the 'hanging' pipeline, due to the collection exercise not doing what it's supposed to after the sample upload. Although this doesn't fix the CI pipeline issues, it definitely eliminates a _potential_ production …
> Fix potential dead heat problem when processing sample units

- src/main/resources/application-cloud.yml
- src/main/resources/application.yml
This is an out of date module/dependency and it is recommended to use the alternative one in the PR instead.
This mainly provides support for 'if exists' in SQL for database for when we do database transactions/migrations etc.
Updated to use correct dependency
- `mvn clean install` and check if all builds successfully
Card: https://trello.com/c/QwluwHSN/509-upgrade-postgresql-hibernate-dialect-from-deprecated-to-v9-for-all-java-services-s
> Added undeprecated database platform instead of current one in place

- manifest-template.yml
In Preprod and prod, the app memory has been manually increased to 2Gb.  If the app crashes then it restarts with the default memory as specified in the manifest (currently 1Gb) - this isn't enough so collection exercise falls over and large parts of the system become unusable.  This work increases the default memory to 2Gb.
- Everything should work as normal
> Increase the app memory in the manifest file from 1Gb to 2Gb

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/repository/SampleUnitRepository.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnits.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidationScheduler.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnitsTest.java
The 'validation' of the samples was spaghetti code and highly inefficient.
Given the need to load large samples for ASHE etc. it seemed prudent to refactor all the code that the lies on the sample load pipeline, to make it more performant and reliable.
In the course of the refactoring, a number of bugs were spotted, such as inability to recover from momentary connection problems with the Survey, Collection Instrument and Party services - these should retry without manual intervention.
The code was inefficient, badly performant, hard to understand, maintain, and it did not handle errors well.
Major refactoring of the `ValidateSampleUnits` class.
Sadly it's still not quite honouring the single responsibility principle, but the code is a lot less complex and should make future refactoring …
> Refactor sample validation

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnits.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnitsTest.java
A bug had been introduced as part of performance improvement work, intended to speed up the amount of time it takes to validate a sample. The bug was putting the same collection instrument onto every sample, regardless of form type.
The cache has been enhanced so that it caches collection instruments down to a form type granularity.
Load a sample with multiple form types. Check that the resulting cases have the correct collection instruments associated against them.
Trello: https://trello.com/c/sySrEfGS
Root cause of bug: https://github.com/ONSdigital/rm-collection-exercise-service/pull/142
> BUG: same collection instrument was being used for every sample in a collex

- _infra/helm/templates/deployment.yaml
migration work. spinnaker was failing to deploy the service due to missing label.
> add missing app label which was failing deployment

- _infra/helm/collection-exercise/Chart.yaml
- _infra/helm/collection-exercise/templates/deployment.yaml
- _infra/helm/collection-exercise/values.yaml
Adds kube_dns addresses for all connecting services to allow us to have circular references
> Add DNS entries

- _infra/helm/collection-exercise/templates/deployment.yaml
- _infra/helm/collection-exercise/values.yaml
The helm charts needed to have the option of selecting different repos when a developer is testing changes.
- The `deployment.yaml` now switches to the devRepo if the `latest` tag is not set.
- Added the devRepo to `values.yaml`. As of now, it is the same as the current image's repo, but will be different in prod and pre-prod.
[Trello card](https://trello.com/c/fLbRN0qG)
> added devRepo

- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/NudgeEmailValidator.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/NudgeEmailValidatorTest.java
bugfix for warning on nudge emails: timestamps show as UTC, not BST
Converted timestamps to dates (as you can't set a timezone on a timestamp), and in error message printed GoLive and ReturnBy dates in GMT, with same format as timestamps
- In sandbox Response Ops, create a new collection exercise, and schedule nudge email for before GoLive or after ReturnBy 
- A red error message will appear asking you to correct the error: check that GoLive and ReturnBy dates are correctly displayed
- https://collaborate2.ons.gov.uk/jira/browse/RAS-241
> Format timestamp output as GMT to warn on NudgeEmail

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/collection-exercise/Chart.yaml
Replacing `set-env` command in GH Actions, disabled this week for security reasons.
- https://trello.com/c/5Pj2VUx5
> replace deprecated cmd in GitHub Actions

- IMPROVEMENTS.md
- _infra/helm/collection-exercise/Chart.yaml
- src/main/resources/database/changes/release-12/changelog.yml
- src/main/resources/database/changes/release-12/remove_report_table_and_procedures.sql
The MI reporting system isn't used in RASRM, so there is no need for it and any related tables/ procedures. From what I could tell, there was no Java code relating to these tables/procedures on the service itself.
* Created database migration to drop three tables (`report`, `reporttype` and `messagelog`) and two procedures (`generate_collectionexercise_mi` and `logmessage`).
* Removed a line from the `improvements.md` about removing the `report` and `reporttype` tables, as that will be done here. Also removed a mention of the `messagelog` table.
[Trello card](https://trello.com/c/ZE7RDTVg)
> created database migration for deleting tables and procedures

- .github/workflows/main.yml
- _infra/helm/collection-exercise/Chart.yaml
During the release step tag the generated docker image as both the release version and latest. 
Run a release
> Docker tag latest at the same time as the release

- _infra/helm/collection-exercise/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/PartySvcClient.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/distribution/SampleUnitDistributor.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnits.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/client/PartySvcClientTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/distribution/SampleUnitDistributorTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnitsTest.java
The `/parties/type/{type}/ref/{ref}` endpoint in party is being removed in favour  of `/businesses/ref/{ref}`.  This PR changes over to it.  Functionally there should be no change as those 2 endpoints have been mapped to the same function in party for months now.
> Change party url to business url

- _infra/helm/collection-exercise/Chart.yaml
- _infra/helm/collection-exercise/templates/deployment.yaml
- _infra/helm/collection-exercise/values.yaml
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/CollectionExerciseApplication.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/SampleSvcClient.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/GCP.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/SampleSummaryActivationPublisher.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/SampleSummaryStateReceiver.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/dto/SampleSummaryStatusDTO.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/representation/SampleSummaryActivationDTO.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleSummaryService.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleSummaryValidationException.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/change/SampleSummaryDistributionException.java
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/client/SampleSvcClientTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/message/SampleSummaryActivationPublisherTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/message/SampleSummaryStateReceiverTest.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleSummaryServiceTest.java
Move the communication between sample and collection exercise to pub sub
1. Deploy and configure the sample v2 enabled flag to true
1. Run acceptance tests
https://trello.com/c/8dkkqOpl/605-ce-sample-convert-communication-to-pubsub
> Moving sample v2 communication to pubsub

- _infra/helm/collection-exercise/Chart.yaml
- src/main/resources/application.yml
The endpoint that gives casegroups for a given collection exercise id will only give you the ones in IN_PROGRESS and NOT_STARTED. Collection exercise needed one where it would return them all regardless of state. This PR uses the new (temporary) endpoint added in case to get the full count
> Update endpoint that is used to get cases

- README.md
- _infra/helm/collection-exercise/Chart.yaml
change the location of the api file in the read me to the correct one
https://trello.com/c/nYqgmTOz/925-s48-update-rm-collecion-exercise-service-high-level-documentation
> update API location in readme

- _infra/helm/collection-exercise/Chart.yaml
- _infra/helm/collection-exercise/templates/deployment.yaml
- _infra/helm/collection-exercise/values.yaml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/EventServiceTest.java
The `deprecateAction` feature flag needed to be removed).
[Card](https://trello.com/c/gto4DbE1)
> remove action deprecated flag

- _infra/helm/collection-exercise/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
The logging for an event not being ready was fine in dev when you had like 10 lines, but in production environments it spams 1000s of lines every minute that aren't very helpful.
> Remove excess logging events that are not ready to be excuted

- .github/workflows/main.yml
- _infra/helm/collection-exercise/Chart.yaml
Currently on a push to a PR each repo builds to latest in onsrasrm-management, however this is the default artifact for all builds when using spinnaker. This means if any change to the charts are made and a PR is created it can and will break dev for everyone. 
Check the build (Publish dev Chart) and make sure it is writing naming the artifact correctly, it should be collection-exercise-pr-300.tgz. You can also check on GCP in ons-rasrmbs-management that the artifact was written out at the right time
> Update publish dev chart

- _infra/helm/collection-exercise/Chart.yaml
- diagrams/collection-exercise-new-states.puml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/state/CollectionExerciseStateTransitionManagerFactory.java
It was found that when uploading a SEFT CI and a sample, with different form types, they failed validation (as expected). However, when trying to correct the issue by uploading the correct files, an error was thrown. It was being caused by the state of the CE being set to failed validation and needs to be changed to a state of scheduled.
I have changed the code, so that the failed validation state of the CE reverts back to a scheduled event. This will allow editing of the uploads without any exceptions/errors.
1. Set up a CE with correct outlined times and dates
2. Uploaded SEFT form type 0001
3. Uploaded sample looking for form type 0002
4. Hit the “set ready for live” button or if didn’t appear, hit the "edit date" MPS date and press “Save” the button should now be visible 
5. I pressed …
> BUG: Setting CE to live with wrong CI causes errors

- _infra/helm/collection-exercise/Chart.yaml
- _infra/helm/collection-exercise/templates/process-events-cronjob.yaml
This PR updates the CronJob version from v1beta to v1
Deploying to case via helm, ```helm install collection-exercse ./_infra/helm/collection-exercse``` The change from v1beta to v1 was tested here aswell https://github.com/ONSdigital/ras-party/pull/390
> RAS-720 update Cronjob to v1

- _infra/helm/collection-exercise/Chart.yaml
- _infra/helm/collection-exercise/templates/hpa.yaml
Update autoscaling from v2beta2 to v2
The HPA change has already been proven here https://github.com/ONSdigital/ras-party/pull/389, but can be done again if required, just deploy via helm
> Update HPA to v2

- _infra/helm/collection-exercise/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseInstrumentReceiverEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/ExceptionHandler.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/dto/CollectionInstrumentMessageDTO.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/message/ExceptionHandlerTests.java
This PR removes the collection instrument id from the message and logging. 
We now update multiple collection instruments at a time which makes this largely redundant. Calling the endpoint multiple times as we have been doing recently is inefficient as it is forcing it to do state checks each time when it should be done just one
Additionally having the uuid of another services object is a bit unusual, specially as it is only used for the logs, that logging should be captured by the CI service, and this one should log what called it and what it affects in its service
N.B This service needs further work as it receives a call from CI and then makes a call back to CI, it shouldn't be doing that and be provided the details it needs on the first call, however as this is a bug fix for something …
> RAS-728 Ready for live button not appearing

- _infra/helm/collection-exercise/Chart.yaml
A conflict wan't picked up merge and the action fired
Make sure 13.0.4 is the next version
> Manually bump version to 13.0.4

- _infra/helm/collection-exercise/Chart.yaml
- openapi.yml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/SampleSvcEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/dto/SampleSummaryReadinessDTO.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseClient.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointIT.java
This PR adds the the endpoint that the sample service uses to notify when the sample is ready and loaded so that when a sample is loaded in response operations, and all other values are loaded, the `Set Ready for live` button appears.
- Deploy this PR to your environment
- Deploy https://github.com/ONSdigital/rm-sample-service/pull/248 to your environment
- Must be deployed last
- Deploy https://github.com/ONSdigital/response-operations-ui/pull/888 to your environment
- Set up a collection exercise in this order
- Required event dates
- A collection instrument
- A sample file
- Ensure the sample has loaded
- There is no `Refresh` link at the top of the page
- The `Set ready for live` button appears and the collection exercise
[RAS-638](https://jira.ons.gov.uk/browse/RAS-638)
> RAS-638 Investigate how "Ready for live" button works, when replacing sample file (track time)

- _infra/helm/collection-exercise/Chart.yaml
- src/main/resources/database/changelog-master.yml
- src/main/resources/database/changes/release-21/add_primary_key_to_supplementary_dataset_table.sql
- src/main/resources/database/changes/release-21/changelog.yml
The new collectionexercise.supplementarydatset table does not have a primary key.
Add a new Liquibase delta to correct this.
Deploy this PR to env, 
check if constraint has been added to database table supplementarydatset
run the acceptance test should set up a collecton excercise you can use to test supplementary data service 
publish this message to supplementary-data-service-{env}
{
"survey_id": "139",
"period_id": "1912",
"form_types": [
"0001"
],
"title": "Test dataset for survey id 009 period 220823",
"sds_published_at": "2023-08-22T14:46:36Z",
"total_reporting_units": 2,
"schema_version": "v1.0.0",
"sds_dataset_version": 4,
"filename": "373d9a77-2ee5-4c1f-a6dd-8d07b0ea9793.json",
"dataset_id": "b9a87999-fcc0-4085-979f-06390fb5dddd"
}
This message should work with the 139 QBS period …
> add changeset to add primary key to supplementary dataset table

- _infra/helm/collection-exercise/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/SampleSvcClient.java
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
Reverts ONSdigital/rm-collection-exercise-service#326
This PR needed to be reverted because I only changed the debugging levels for the purpose of testing things out in preprod, but we don't want these logging statements showing up in prod.
To test, run acceptance tests and check the logs for the pod. They shouldn't show up (use CTRL+F and type the logging messages to check) becuase they've gone back to being debug messages.
> Revert "change debug to info"

- _infra/helm/collection-exercise/Chart.yaml
- pom.xml
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseClient.java
org.json has vulnerabilities and hasn't been updated for years. jackson.json is up to date so this replaces it.
Run unit/integration tests
RAS-924
> Replace org.json with jackson.json due to vulnerabilities

- .github/workflows/comment.yml
- .github/workflows/main.yml
- .github/workflows/manual.yml
- _infra/helm/collection-exercise/Chart.yaml
This PR replaces set-output within the .github workflow file with environment variables to fix a deprecation with set-output. It also updates actions/auth to v2.
Check the github builds for any deprecation warnings and ensure the workflow works after the changes.
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-915
> Update set-output to environment variables

- _infra/helm/collection-exercise/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SupplementaryDatasetService.java
- src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/SupplementaryDatasetServiceTest.java
**This PR contains verified commits that were created and reviewed on branch of PR #338**
Changes how we check if an SDS in already linked to a collection exercise since the collection exercise already has the liked sds in scope through the ORM instead of querying the database every time.
- Deploy to your env
- Run the acceptance tests
- publish a message to your sds topic
```
{
"survey_id": "139",
"period_id": "1912",
"form_types": [
"0001"
],
"title": "Quarterly Business Survey | QBS | 139 | 1912",
"sds_published_at": "2023-08-24T11:55:00Z",
"total_reporting_units": 1,
"schema_version": "v1.0.0",
"sds_dataset_version": 2,
"filename": "eccb61ad-4eb3-4714-8afd-8c8426960b43.json",
"dataset_id": "eccb61ad-4eb3-4714-8afd-8c8426960b43"
}
```
- make sure that in the logs there is no linked …
> RAS-917 SupplementaryDatasetService dataset call via existsByExerciseFK not required

- _infra/helm/collection-exercise/Chart.yaml
- _infra/helm/collection-exercise/templates/loadbalancer.yml
- _infra/helm/collection-exercise/templates/service.yaml
- _infra/helm/collection-exercise/values.yaml
Changing collection exercise service to a NodePort instead of a ClusterIP to allow access from outside the kubernetes environment to give access to the cloud function
Follow test for https://github.com/ONSdigital/ras-rm-cloud-functions/pull/52
https://jira.ons.gov.uk/browse/RAS-1184
> RAS-1184 Seft-ci-ingestion cloud function: Introduce HTTP client to retrieve collex

- .github/workflows/main.yml
- docker-compose-down.sh
- docker-compose-up.sh
- docker-compose.yml
- pom.xml
This PR replaces our use of the `docker-compose-maven-plugin` as that is still using `docker-compose` that has been removed
Check the build
[RAS-1238](https://jira.ons.gov.uk/browse/RAS-1238)
> RAS-1238 Update to docker compose from docker-compose

- _infra/helm/collection-exercise/Chart.yaml
- _infra/helm/collection-exercise/templates/loadbalancer.yml
- _infra/helm/collection-exercise/values.yaml
Allows us to disable the collection exercise load balancer
Helm install collection exercise after updating `values.yaml`
- `loadBalancer.enabled: false`
- `env: dev`
- `namespace: <your-namespace>`
- `image.tag: pr-343`
Make sure that there is no collection exercise load balancer service deployed when you run `kubectl get sercives`
[RAS-1247](https://jira.ons.gov.uk/browse/RAS-1247)
> making collection exercise load balancer configurable

- .github/workflows/main.yml
- .github/workflows/manual.yml
- _infra/helm/collection-exercise/Chart.yaml
- _infra/helm/collection-exercise/values.yaml
Migrates the image from google container registry to google artifacts registry.
Deploy your environment
Deploy this pr with the config branch https://github.com/ONSdigital/ras-rm-config/pull/274
Update the deployment yaml to point to the correct image location `europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images/`
Check image is in the correct project artifact registry
N.B. there are references to both survey and pubsub emulator within collex. We will need to loop back and update these once those have been moved to GAR. 
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-1349
> Migrate GCR to GAR

- .github/CODEOWNERS
- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- .github/workflows/manual.yml
- _infra/helm/collection-exercise/Chart.yaml
Updates all deprecated instances of actions/cache to v4
Adds codeowners file
Check the github actions builds for successful use of actions/cache
Check codeowners file
[RAS-1409](https://jira.ons.gov.uk/browse/RAS-1409)
> Upgrade actions cache

- _infra/helm/collection-exercise/Chart.yaml
- docker-compose.yml
PubSub emulator has been migrated from GCR to GAR
Check the tests run in GHA and locally
https://jira.ons.gov.uk/browse/RAS-1423
> Use migrated GAR pubsub-emulator image

- _infra/helm/collection-exercise/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
Swaps out the get collection exercises by survey id with get collection exercises by survey ids to reduce the number of calls to collection exercise from one per survey the respondent has, to just one for all the surveys the respondent has
- deploy this pr and https://github.com/ONSdigital/ras-frontstage/pull/1042 to your environment
- run acceptance tests
- set up another CE for QBS and one for a new survey
- log into frontstage and make sure the user interface looks the same on the todo and history pages
- go to the database and set the collection exercise state to ENDED
- make sure it doesn’t show up in the Todo or History pages in frontstage
[RAS-1401](https://jira.ons.gov.uk/browse/RAS-1401)
> Extend get ces for surveys
