ONSdigital/rm-collection-exercise-service

.travis.settings.xml
.travis.yml
README.md

On a successful build on master the docker image should be pushed up

Travis build, test and push docker image

---

Dockerfile

Docker java debug

---

src/main/resources/application.yml

Align default port numbers for all apps. Port numbers for all apps can be found here: https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/94863418/Developer+Environment+Port+Mappings

aligning ports

---

API.md
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/CollectionInstrumentSvcRestClientImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/PartySvcRestClientImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/SampleSvcRestClientImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/SurveySvcRestClientImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/CollectionExercise.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/SampleLink.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseExecutionEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/repository/CollectionExerciseRepository.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/CollectionExerciseService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java
src/main/resources/database/changelog-master.yml
src/main/resources/database/changes/release-10.49.2/changelog.yml
src/main/resources/database/changes/release-10.49.2/us002a-add-columns-to-collection-exercise.sql
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseExecutionEndpointUnitTests.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImplTest.java
src/test/resources/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.CollectionExercise.post.json
src/test/resources/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.CollectionExerciseDTO.post-missing-survey.json
src/test/resources/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.CollectionExerciseDTO.post.json
src/test/resources/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseExecutionEndpointUnitTests.SampleUnitsRequestDTO.json
src/test/resources/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImplTest.CollectionExercise.json
src/test/resources/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImplTest.CollectionExerciseDTO.json
src/test/resources/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImplTest.Survey.json

Added POST, PUT and DELETE operations to the collection exercise service

Us002a load collection exercise data

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java

Previously just returned summary with 3 fields

Changed /collectionexercises/survey/{id} to return full DTO

---

pom.xml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImpl.java

Please review code for the following task for US004: Load Events
GET /collectionexercises/{collexId}/events/{eventTag} --> Retrieve event
PUT /collectionexercises/{collexId}/events/{eventTag} --> Update the event date
DELETE /collectionexercises/{collexId}/events/{eventTag} --> Delete event
I have changed in the following three classes
CollectionExerciseEndpoint.java
EventService.java
EventServiceImpl.java

Us004 load events faisal

---

pom.xml

Simple update to bring the collection exercise service in line with rm-collectionexercisesvc-api following the automated release of the latter

Updated pom following rm-collectionexercisesvc-api release

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/CollectionExerciseApplication.java

the service should not be throwing an error if an unexpected fields has been added as this is not an api breaking change

handle unexpected fields correctly

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/CollectionExerciseService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventChangeHandler.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/change/PublishEventToQueueHandler.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/change/ScheduledStartDateHandler.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImplTest.java

NOTE: this PR contains code required to sign off US004 so I'd like to get this pushed through today if possible :-)
Created new mechanism for executing code when events change etc and used
it to update scheduledStartDate and also changed existing publish of
messages to rabbit queue to use it too
Started adding unit tests for EventService
Fixed broken unit test
PS. the lack of tests for EventServiceImpl and related classes has been noted - they will be added in due course, either in this pull request or the next.

Implemented setting of scheduledStartDate from mps event

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/change/ScheduledStartDateHandler.java

Cherry pick of fix to set most dates on collection exercise from incoming events

Set a whole bunch of other dates from incoming events

---

.maven.settings.xml
.travis.yml
Jenkinsfile

Jenkins polls every minute for changes
A pipeline to
1. Build and unit test the source code
1. Deploy the snapshot artifact
1. Deploy to dev CF
1. Deploy to CI CF based on user feedback
1. Create release artifact based on user feedback
1. Deploy to TEST based on user feedback

Jenkins pipeline

---

API.md
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/repository/CollectionExerciseRepository.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/repository/SampleUnitRepository.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/CollectionExerciseService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/SampleServiceImpl.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java

As an: internal user
I need: to be able to view the surveys & CEs associated to the RU Ref
So that: I can understand for any RU Ref, the surveys and CEs  they are selected for

Us045 view ces for ru

---

pom.xml

dependent on: https://github.com/ONSdigital/rm-collectioninstrumentsvc-api/pull/4

use new CollectionInstrumentsvc-api

---

API.md
pom.xml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/repository/SampleUnitRepository.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/CollectionExerciseService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/SampleServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/state/CollectionExerciseStateTransitionManagerFactory.java

- Added a RESET event to the valid events for collection exercises to allow a collection exercise that has FAILEDVALIDATION to be recovered.
- Added a DTO for describing validation errors that cause collection exercise executions to fail
https://github.com/ONSdigital/rm-collectionexercisesvc-api/pull/10

Added RESET event and validation error DTO

---

src/main/resources/application.yml
src/main/resources/schema.sql

To allow the service to spin up from an empty database

Added schema file

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java

Fixed problem where timezone was being ignored when updating collection exercise events

Fix event timezone parsing

---

docker-compose.yml
pom.xml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/CollectionExerciseApplication.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/AppConfig.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/SampleUploadedInboundReceiver.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseClient.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointIT.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/SampleUploadedInboundReceiverTest.java

Pattern based on SampleEndpointIT.java from the sample service.

Added an integration test to test receiving sample upload finished messages

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/CollectionExerciseService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java

Removing unused method
Remove findCollectionExercisesForParty
unit tests/integration tests should still pass

Delete unused method

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/SampleServiceImpl.java

Tidy up code.
Removed logically impossible tests
* `mvn clean install`

Remove logically impossible checks

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/distribution/SampleUnitDistributor.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/ExerciseSampleUnit.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/domain/ExerciseSampleUnitTest.java

Motivation and Context
======================
The sample unit distributor is a complicated method that can be
simplified with minimal effort.
What has changed
================
This is a simplified version of that method. No logic has changed
How to test?
======================
* mvn clean install
* acceptance tests

Simplify the SampleUnitDistributor

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/CollectionExerciseApplication.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventValidator.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/BusinessEventValidator.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImpl.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointIT.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/BusinessEventValidatorTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImplTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventValidatorTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/MultipleBusinessEventsValidatorTest.java

Add validation for adding Collection Exercise Events.
Additional logic for validating adding of events.
EventValidator Interface added.
Need to review existing update event validation, a new ticket has been raised.

Validate create event2

---

src/main/resources/springintegration/sample-sampleunit-inbound-flow.xml

See https://github.com/ONSdigital/rm-sample-service/pull/68

Handle retries correctly

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/CollectionExerciseApplication.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/ActionSvcRestClientImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/CollectionInstrumentSvcRestClientImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/PartySvcRestClientImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/SampleSvcRestClientImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/impl/SurveySvcRestClientImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/AppConfig.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/Logging.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/distribution/SampleUnitDistributor.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseExecutionEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/CollectionExerciseEventInboundReceiver.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/CollectionExerciseEventPublisherImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/CollectionInstrumentLoadedReceiver.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/SampleUnitPublisherImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/impl/SampleUploadedInboundReceiver.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/schedule/EventJob.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/schedule/SchedulerConfiguration.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/CollectionExerciseServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/EventServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/ExerciseSampleUnitGroupServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/SampleServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/change/PublishEventToQueueHandler.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/change/ScheduledStartDateHandler.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/impl/change/ScheduledStateTransitionHandler.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnits.java
src/main/resources/application-cloud.yml
src/main/resources/application.yml

Using the Godaddy logging package we can now use key value pairs
with .with(). This PR updates all logging to use key value pairs.
updates all logging to use key value pairs.
Ran ITs and ATs.
Make sure logs lines have not been missed.

Update logging to use key value pairs

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventValidator.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/MandatoryEventValidator.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/ReferencePeriodEventValidator.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/ReminderEventValidator.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/EventServiceTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/MultipleMandatoryEventsValidatorTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/MandatoryEventValidatorTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/ReferencePeriodEventValidatorTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/ReminderEventValidatorTest.java

Changed the way the CE event validation process handles exceptions and returns data
Made changes to unit tests to accommodate changes
run unit tests
Manual test with invalid information in resops (accompanying PR) and check correct error message is displayed.
ASAIK tried every possible type of invalid information submitted through the form manually, unit tests in ResOps for 'categories' of errors.
https://trello.com/c/tVq25lkO/791-fix-error-messaging-when-validating-the-ce-event-create-update-forms
ResOps PR: https://github.com/ONSdigital/response-operations-ui/pull/301

Validation exception changes with tests

---

.travis.yml
docker-compose.yml
pom.xml

Image name is not consistent across travis, pom files etc...
build & push image as "eu.gcr.io/census-rm-ci/rm/census-rm-collectionexercisesvc"
**1.** check out branch
**2.** create a temporary commit by adding the following to .travis.yml file (before "- bash <(curl -s https://codecov.io/bash)" line) in "after_success:"  - 
```
- if [ "$TRAVIS_BRANCH" == "image-location-change" ] ; then
docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
docker tag "eu.gcr.io/census-rm-ci/rm/census-rm-collectionexercisesvc" "eu.gcr.io/census-rm-ci/rm/census-rm-collectionexercisesvc:test";
docker push "eu.gcr.io/census-rm-ci/rm/census-rm-collectionexercisesvc:test";
fi
```
and replace "branches" section with -
```
branches:
only:
- master
- image-location-change …
```

Image location change

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java

This deletes a duplicate endpoint

Delete duplicate endpoint

---

pom.xml

Improve security
Upgraded com.fasterxml.jackson.core:jackson-databind to version 2.9.10

fix security issue

---

API.md
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/repository/EventRepository.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointUnitTests.java

This will enable future work on the dashboard

New endpoint

---

_infra/helm/templates/deployment.yaml
_infra/helm/templates/service.yaml

Remove the run service label and the Match env label as there is no matching label to match with

Remove match label

---

_infra/Dockerfile
_infra/helm/templates/deployment.yaml

Remove docker user and set image pull poloicy to always until preprod testing has finished

remove docker user and set always pull policy

---

_infra/helm/templates/deployment.yaml
_infra/helm/templates/service.yaml
_infra/helm/values.yaml

split out db config and create some additional templating

additional templating

---

_infra/helm/collection-exercise/templates/deployment.yaml
_infra/helm/collection-exercise/templates/service.yaml
_infra/helm/collection-exercise/values.yaml

standardise db config

---

_infra/helm/collection-exercise/templates/deployment.yaml
_infra/helm/collection-exercise/templates/service.yaml
_infra/helm/collection-exercise/values.yaml

add redis tempalte

---

_infra/helm/collection-exercise/templates/deployment.yaml
_infra/helm/collection-exercise/values.yaml

add sql proxy

---

_infra/helm/collection-exercise/templates/deployment.yaml
_infra/helm/collection-exercise/values.yaml

Disable zipkin and make it a variable

---

_infra/helm/collection-exercise/templates/deployment.yaml

Fix security config

---

_infra/helm/collection-exercise/values.yaml

The service port needed to be changed to 8080.
Changed service port to 8080.
[Trello card](https://trello.com/c/iBBXBpLll)

changed service port

---

_infra/helm/collection-exercise/Chart.yaml
_infra/helm/collection-exercise/templates/deployment.yaml
_infra/helm/collection-exercise/values.yaml

Allowing the selection of different version numbers will allow code changes to be tasted without needing to commit to master.
- Added if-statement in `deployment.yaml` to select version number based on the presence of the `latest` tag in `values.yaml`.
- Updated chart version number.
- Added `latest` tag to `values.yaml`.
[Trello card](https://trello.com/c/Xlj2T6Gi)

added if-statement for variable versions

---

_infra/helm/collection-exercise/templates/deployment.yaml
_infra/helm/collection-exercise/values.yaml
pom.xml
src/main/resources/application.yml

Zipkin needed to be removed from the various services.
Removed all mentions of Zipkin.
[Trello card](https://trello.com/c/YZ9aio6I)

removed all mentions of zipkin

---

.github/workflows/main.yml
_infra/helm/collection-exercise/Chart.yaml

replace concourse

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/NudgeEmailValidator.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/NudgeEmailValidatorTest.java

Inform user when a nudge email is created for the same date/time

---

.github/workflows/comment.yml
.github/workflows/main.yml
_infra/helm/collection-exercise/Chart.yaml

Make dev docker tag changes

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/representation/ResponseEventDTO.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/validator/NudgeEmailValidator.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseClient.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpointIT.java

collection exercise svc changes for nudge email delete message changes

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/ReminderActionRuleRemover.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/NudgeEmailActionRuleRemoverTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/ReminderActionRuleRemoverTest.java

Delete Functionality for Reminder Emails

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/ReminderActionRuleRemover.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/EventServiceTest.java

Reminder email bug for unhooked component

---

src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/ActionSvcClient.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/ActionSvc.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/lib/action/representation/ActionPlanPutRequestDTO.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/CollectionExerciseService.java
src/main/resources/application.yml
src/test/java/uk/gov/ons/ctp/response/collection/exercise/client/ActionSvcClientTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/CollectionExerciseServiceTest.java

Period name change bug

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/schedule/SchedulerConfiguration.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/NudgeEmailActionRuleCreator.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/NudgeEmailActionTypeRuleGenerator.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/NudgeEmailActionRuleCreaterTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/NudgeEmailActionTypeRuleGeneratorTest.java

Removing Nudge Email letter BSNUL

---

_infra/helm/collection-exercise/Chart.yaml
_infra/spinnaker/deployment-full.json

syncronize default helm chart

---

_infra/helm/collection-exercise/Chart.yaml

manual bump of appVersion

---

.github/workflows/comment.yml
_infra/helm/collection-exercise/Chart.yaml

change from sandbox to dev

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidateSampleUnits.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/validation/ValidationScheduler.java

The validation and transitioning of collection exercises and sample units had way too little logging, making it difficult to diagnose issues when they occur.
This PR updates some of the documentation and adds logging to make it clearer what it's doing, and the state that it's in on failure.

Add logging to sample and collection exercise validation code

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/GoLiveActionRuleCreator.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/MpsActionRuleCreator.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/NudgeEmailActionRuleCreator.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/ReminderActionRuleCreator.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/GoLiveActionRuleCreatorTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/MpsActionRuleCreatorTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/NudgeEmailActionRuleCreaterTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/actionrule/ReminderActionRuleCreatorTest.java

Feature flag now turns off action rule creation

Feature flag away action rule creation

---

_infra/helm/collection-exercise/Chart.yaml
_infra/helm/collection-exercise/templates/deployment.yaml
_infra/helm/collection-exercise/values.yaml

add resource requests for the proxy container

---

_infra/helm/collection-exercise/Chart.yaml
_infra/helm/collection-exercise/templates/hpa.yaml
_infra/helm/collection-exercise/values.yaml

add min replicas

---

_infra/helm/collection-exercise/Chart.yaml
src/main/resources/database/changelog-master.yml
src/main/resources/database/changes/release-14/changelog.yml
src/main/resources/database/changes/release-14/update_existing_events_status.sql

The events that have currently been created have a NOT_SET state. When we do the switch to the new version that talks to case instead of action, we'll need to update existing events to either be:
- PROCESSED (in the case of past events)
- SCHEDULED (in the case of future events)
Liquibase updates to `collectionexercise.event`
- https://trello.com/c/pmXZmR5Y

Event status update existing

---

.github/workflows/comment.yml

add key value support for /deploy command

---

.github/workflows/comment.yml
_infra/helm/collection-exercise/Chart.yaml

Use new github action created specifically for ras-rm pr comments.
https://github.com/ONSdigital/ras-rm-spinnaker-action

new comment action

---

_infra/helm/collection-exercise/Chart.yaml
src/main/resources/database/changelog-master.yml

Adding update existing event status to liquibase

---

.github/workflows/main.yml
Dockerfile
_infra/helm/collection-exercise/Chart.yaml
pom.xml

Updating collection exercise from java 8 to 11
Changes:
Pom.xml - java 11 update including sun microsystem dependencies and jaxb dependencies
docker file - to use jdk 11
main.yaml - Actions yaml to use jdk 11

Updating collection exercise to java 11

---

_infra/helm/collection-exercise/Chart.yaml
pom.xml

Updating lombok version for collection exercise

missed lombok update cause problems

---

_infra/helm/collection-exercise/Chart.yaml

Updating chart version to trigger master build.

updating version to trigger master build

---

.github/workflows/manual.yml

A manual workflow dispatch workflow has been created for a manual trigger of the build if and when required. This can be further refactored once confirmed it works.

manual.yml

---

README.md
_infra/helm/collection-exercise/Chart.yaml

Remove badges

---

.github/workflows/main.yml

Do not ignore charts

---

_infra/helm/collection-exercise/Chart.yaml
_infra/helm/collection-exercise/templates/deployment.yaml

Update sql-proxy from 1.16 to 1.22

---

.github/workflows/main.yml
.github/workflows/manual.yml
_infra/helm/collection-exercise/Chart.yaml
docker-compose.yml
pom.xml

Use GCR images for integration tests
`mvn clean install`
https://trello.com/c/mGQ7YEeN/678-bug-use-gcr-images-for-integration-tests

GCR images for integration tests

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/CollectionExercise.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/Event.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/ExerciseSampleUnit.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/ExerciseSampleUnitGroup.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/SampleLink.java
src/main/resources/database/changelog-master.yml
src/main/resources/database/changes/release-16/changelog.yml
src/main/resources/database/changes/release-16/rename_database_columns.sql

The database columns needed to be standardised with underscores between words.
Deploy and check that the database migration works
[Card](https://trello.com/c/NTJ8Nlsj)

Renaming database columns

---

.github/workflows/main.yml
_infra/helm/collection-exercise/Chart.yaml

Update chart versions automatically

---

_infra/helm/collection-exercise/Chart.yaml
_infra/helm/collection-exercise/templates/deployment.yaml
_infra/helm/collection-exercise/values.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/SampleSvcClient.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/AppConfig.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/SampleSvc.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseExecutionEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleSummaryService.java
src/main/resources/application.yml
src/test/java/uk/gov/ons/ctp/response/collection/exercise/client/SampleSvcClientTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleSummaryServiceTest.java

Integration with v2 of the sample service
Deploy this PR and the sample service v2 PR to your Kubernetes environment and run the acceptance tests
https://trello.com/c/lsGFcRzR/440-s39-ce-sample-distribution-phase

Sample v2 integration

---

_infra/helm/collection-exercise/Chart.yaml
_infra/helm/collection-exercise/templates/deployment.yaml

Update environment variable

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleSummaryService.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleSummaryServiceTest.java

Sample V2 Bug fix - set sample unit count on activation

Add sample unit count to collection exercise on activation

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/client/SampleSvcClient.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/SampleSvc.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/lib/sample/representation/SampleUnitDTO.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleService.java
src/main/resources/application.yml
src/test/java/uk/gov/ons/ctp/response/collection/exercise/client/SampleSvcClientTest.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/SampleServiceTest.java

If a sample fails validation then call sample service to get the failed samples.
Deploy to your env
load a sample file which will failed (i.e. an invalid form type)
https://trello.com/c/Q5mkQDUb/900-bug-return-sample-unit-validation-errors-to-ce

Sample Unit validation

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/repository/EventRepository.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/EventServiceTest.java

Change list to stream

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/EventServiceTest.java

Add check for null sample size

---

_infra/helm/collection-exercise/Chart.yaml
_infra/helm/collection-exercise/templates/deployment.yaml
_infra/helm/collection-exercise/values.yaml
docker-compose.yml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/CollectionExerciseApplication.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/config/GCP.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/CaseActionEventStatusReceiver.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/message/dto/CaseActionEventStatusDTO.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/repository/EventRepository.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/representation/EventDTO.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
src/main/resources/application.yml
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseClient.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/message/CaseActionEventStatusReceiverIT.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/EventServiceTest.java
src/test/resources/uk/gov/ons/ctp/response/collection/exercise/messages/eventStatusMessage.json

https://trello.com/c/qjeSODjt/964-provide-feedback-logic-for-action-via-collection-exercise

Update event status

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/representation/EventDTO.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/message/CaseActionEventStatusReceiverIT.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/service/EventServiceTest.java

https://trello.com/c/9H8g3qTR/1131-bug-status-change-merge-failing-in-preprod

Status bug fix

---

_infra/helm/collection-exercise/Chart.yaml
diagrams/collection-exercise-new-states.puml
openapi.yml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java

correct one of endpoints as part of api cleanup
https://trello.com/c/nYqgmTOz/925-s48-update-rm-collecion-exercise-service-high-level-documentation

cleanup api file

---

.github/workflows/comment.yml
.github/workflows/main.yml
.github/workflows/manual.yml
_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/representation/EventDTO.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java

https://trello.com/c/rjpW5h7r/1415-rops-event-status-survey-screen

changes for event status on rops

---

_infra/helm/collection-exercise/Chart.yaml
_infra/helm/collection-exercise/templates/deployment.yaml

Upgrade cloudsql proxy

---

.github/workflows/main.yml
_infra/helm/collection-exercise/Chart.yaml

Removal of deprecated github action
https://trello.com/c/JyPxSmDA/2298-replace-soon-to-be-deprecated-set-output-in-github-actions

Fix setoutput

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/representation/CollectionExerciseDTO.java

Changes to the front-end mean that a Collection Exercise can now be created without a user description
https://trello.com/c/3b7gH0cK/2264-rops-design-improvement-collection-exercise-overview-page

Make user description field optional

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/SampleSvcEndpoint.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseClient.java

Review changes for the collection exercise part of the card
https://github.com/ONSdigital/rm-collection-exercise-service/pull/319
[RAS-638](https://jira.ons.gov.uk/browse/RAS-638)

RAS-638 Investigate how "Ready for live" button works, when replacing sample file (track time)

---

_infra/helm/collection-exercise/Chart.yaml

manaully bump version

---

_infra/helm/collection-exercise/Chart.yaml
pom.xml

Swaps mockito inline to mockito core and adding bytebuddy to allow it to run
- run `mvn clean verify`
- deploy to your env and run the acceptance tests
https://jira.ons.gov.uk/browse/RAS-920

RAS-920 Collection exercise change mockito-inline to mockito-core for Java

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/CollectionExerciseService.java
src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/EventService.java
src/main/resources/application.yml
src/test/java/uk/gov/ons/ctp/lib/common/FixtureHelper.java
src/test/java/uk/gov/ons/ctp/response/collection/exercise/lib/common/FixtureHelper.java

Updating the logging level from debug to info
deploy to you environment and run the acceptance tests, make sure that no `debug` level logs appear in the collection exercise logs
https://jira.ons.gov.uk/browse/RAS-930

RAS-930 Reduce collection exercise logging level to info

---

_infra/docker/Dockerfile
_infra/helm/collection-exercise/Chart.yaml

This PR migrates off the deprecated open docker image to eclipse.
Run both the acceptance and local tests. 
Check the new image is smaller. 
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-969

Update docker image to eclipse-temurin17

---

.github/workflows/main.yml
_infra/helm/collection-exercise/Chart.yaml

Replacing the unmaintained create release action with a github command that does the same and updating the setup-gcloud
Check the build
https://jira.ons.gov.uk/browse/RAS-1011

RAS-1011 Replace unmaintained actions/create-release and update google-github-actions/setup-gcloud

---

.github/workflows/main.yml
_infra/helm/collection-exercise/Chart.yaml

Adding secrets and updating GHA workflow to verify the pr bot
Check the pr bot is verified in the commit history
[RAS-917](https://jira.ons.gov.uk/browse/RAS-917)

Adding signature for pr bot to be verified

---

_infra/helm/collection-exercise/Chart.yaml

Increases chart version after merge conflict.
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&selectedIssue=RAS-1349

Resolve chart conflict

---

_infra/helm/collection-exercise/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java

Reverts ONSdigital/rm-collection-exercise-service#351

Revert "Extend get ces for surveys"

---

.github/workflows/codeql-analysis.yml
.github/workflows/comment.yml
.github/workflows/main.yml
.github/workflows/manual.yml
_infra/helm/collection-exercise/Chart.yaml

Pinning GHA versions to commit references
Check GHA
[RAS-1418](https://jira.ons.gov.uk/browse/RAS-1418)
**Not a production candidate**

RAS-1418 EPIC: Unpinned tag for a non-immutable Action in workflow

---

.github/workflows/main.yml
_infra/helm/collection-exercise/Chart.yaml

This PR adds the dependabot-specific workflow for this service
Can't be tested until merged in. Look over the PR and check that it makes sense, and is similar to the [mock-EQ service's GA workflow](https://github.com/ONSdigital/ras-rm-mock-eq/blob/main/.github/workflows/main.yml).
[Card](https://officefornationalstatistics.atlassian.net/jira/software/c/projects/RAS/boards/1943?selectedIssue=RAS-1669)

add dependabot workflow
